# Generated by Django 3.2.3 on 2021-06-29 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="total",
        ),
        migrations.AddField(
            model_name="game",
            name="points",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
