# Generated by Django 3.2.3 on 2021-06-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_auto_20210628_2101"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="cps",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="game",
            name="points",
            field=models.IntegerField(default=0),
        ),
    ]
